config/routes.rb
Rails.application.routes.draw do
    root to: 'posts#index'
    
    get 'about', to: 'staticspages#about'

    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    
    get 'signup', to: 'users#new'
    resources :users, only: [:show, :new, :create, :edit, :update] do
        member do 
            get :likes
        end
    end
    
    get 'post/tag/:name', to: 'posts#tag'
    get 'posts', to: 'posts#new'
    resources :posts, only: [:index, :new, :create, :destroy]
    
    resources :favorites, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    with_options length: { maximum: 10, message: '文字数が多すぎます' } do 
        with_options format: { with: /\A[ぁ-んァ-ン一-龥]/, message: 'に使用できない文字が入ってます。または文字が入っていません。'} do
            validates :content 
            validates :two_content
            validates :three_content
        end
        with_options format: { with: /\A[ぁ-んァ-ン一-龥]+|\A\z/, message: 'に使用できない文字が入ってます。' } do
            validates :four_content
            validates :five_content
        end
    end
    validates :hashtag, presence: { message: 'が入力されていません。'}
    
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :likes, through: :favorites, source: :user, dependent: :destroy
    has_many :tag_posts, dependent: :destroy
    has_many :tags, through: :tag_posts, dependent: :destroy
    
    def favorite(user)
        favorites.find_or_create_by(user_id: user.id)
    end
    
    def unfavorite(user)
        favorites.find_by(user_id: user.id).destroy
    end
    
    def likes?(user)
        favorites.where(user_id: user.id).exists?
    end
    
    after_create do
        post = Post.find_by(id: self.id)
        tags = self.hashtag.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
        tags.uniq.map do |t|
            tag = Tag.find_or_create_by(hashname: t.downcase.delete('#'))
            post.tags << tag
        end
    end
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :tag_posts, dependent: :destroy
    has_many :posts, through: :tag_posts, dependent: :destroy
end

app/models/tag_post.rb
class TagPost < ApplicationRecord
    belongs_to :post
    belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: { maximum: 15, message: 'の文字数は最大15文字です。' }
    validates :email, presence: true, length: { maximum: 255, message: 'が空欄です。' },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: 'の入力方法が間違っています。' },
                      uniqueness: { case_sensitive: false, message: 'はすでに存在します。' }
    validates :profile, length: { maximum: 250, message: 'の文字数は最大250文字です。' }
    has_secure_password
    mount_uploader :image, ImagesUploader
    has_many :posts
    has_many :favorites, dependent: :destroy
    has_many :likes, through: :favorites, source: :post, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    include SessionsHelper
    
    private
    
    def require_user_logged_in
        unless logged_in?
            flash[:info] = 'その操作はログイン時のみ可能です'
            redirect_to login_url
        end
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    before_action :require_user_logged_in
    
    def create
        post = Post.find(params[:post_id])
        post.favorite(current_user)
        flash[:success] = 'お気に入りに登録しました'
        redirect_to '/'
    end

    def destroy
        post = Post.find(params[:post_id])
        post.unfavorite(current_user)
        flash[:danger] = 'お気に入りを解除しました'
        redirect_to '/'
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :require_user_logged_in, only: [:new, :create]
    before_action :correct_user, only: [:destroy]
    
    def index 
        @posts = Post.order(id: :desc).page(params[:page]).per(20)
    end
  
    def new
        @post = Post.new
    end

    def create
        @post = current_user.posts.build(post_params)
    
        if @post.save
            flash[:success] = '投稿に成功しました'
            redirect_to '/'
        else
            flash.now[:info] = '投稿に失敗しました'
            render :new
        end
    end

    def destroy
        @post.destroy
        flash[:danger] = "投稿を削除しました"
        redirect_back(fallback_location: root_path)
    end
  
    def tag
        @hashtag = Tag.find_by(hashname: params[:name])
        @post  = @hashtag.posts.order(id: :desc).page(params[:page]).per(20)
    end
  
    private 
  
    def post_params
        params.require(:post).permit(:content, :two_content, :three_content, :four_content, :five_content, :tag_ids, :hashtag, :haiku)
    end
  
    def correct_user
        @post = current_user.posts.find_by(id: params[:id])
        unless @post
            redirect_to root_url
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        email = params[:session][:email].downcase
        password = params[:session][:password]
        if login(email,password)
            flash[:success] = 'ログインに成功しました'
            redirect_to @user
        else
        flash.now[:danger] = 'ログインできませんでした'
        render :new
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = 'ログアウトしました'
        redirect_to '/'
    end
  
    private
  
    def login(email,password)
        @user = User.find_by(email: email)
        if @user && @user.authenticate(password)
            session[:user_id] = @user.id
            return true
        else
            return false
        end
    end
end

app/controllers/staticspages_controller.rb
class StaticspagesController < ApplicationController
    def about
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_user_logged_in, only: [:show, :edit]
    before_action :correct_user, only: [:edit]
    before_action :set_user, only: [:show, :update, :likes]
    
    def set_user
        @user = User.find(params[:id])
    end
    
    def show
        @post = @user.posts.order(id: :desc).page(params[:page]).per(20)
    end

    def new
        @user = User.new
    end
  
    def create
        @user = User.new(user_params)
    
        if @user.save
            flash[:success] = "登録に成功しました"
            redirect_to @user
        else
            flash.now[:danger] = "登録に失敗しました"
            render :new
        end
    end

    def update
        @user = current_user
        if @user.update(user_params)
            flash[:success] = "更新しました"
            redirect_to @user
        else
            flash.now[:danger] = "更新できませんでした"
            render :new
        end
    end
  
    def likes
        @likes = @user.likes.page(params[:page]).per(9)
    end
  
    private
  
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :profile)
    end
  
    def correct_user
        @user = current_user
        unless @user
            redirect_to root_url
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        !!current_user
    end
end

app/views/favorites/_favorite_button.html.erb
<% if post.likes?(current_user) %>
    <%= form_with(model: post.favorites.find_by(post_id: post.id), local: true, method: :delete) do |f| %>
        <%= hidden_field_tag :post_id, post.id %>
        <%= button_tag type: "submit", class: "btn btn-default btn-s-md" do %>
            <i class="fas fa-heart"></i>
        <% end %>
    <% end %>
<% else %>
    <%= form_with(model: post.favorites.build, local: true, method: :post) do |f| %>
        <%= hidden_field_tag :post_id, post.id %>
        <%= button_tag type: "submit", class: "btn btn-default btn-s-md" do %>
            <i class="far fa-heart"></i>
        <% end %>
    <% end %>
<% end %>
    

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
    <div id="error_explanation" class="alert alert-warning">
        <ul class="mb-0">
            <% model.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="col-sm-10 offset-sm-1">
    <nav class="navbar navbar-expand-sm navbar-dark" >
        <a class="navbar-brand" href="/">詩歌<%= image_tag 'logo.png', id: "logo" %></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <% if logged_in? %>
                <li class="nav-item"><%= link_to '投稿', posts_path, class: 'nav-link' %></li>
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
                    <ul class="dropdown-menu dropdown-menu-right">
                        <li class="dropdown-item"><%= link_to 'マイページ', user_path(current_user) %></li>
                        <li class="dropdown-item"><%= link_to 'お気に入り', likes_user_path(current_user) %></li>
                        <li class="dropdown-item"><%= link_to '使い方', about_path %></li>
                        <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
                    </ul>
                </li>
                <% else %>
                <li class="nav-item"><%= link_to '新規登録', signup_path, class: 'nav-link' %></li>
                <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
                <% end %>
            </ul>
        </div>
        
        
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Shiika</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
    
        <%= favicon_link_tag('favicon.ico') %>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    </head>
    <body>
        <%= render 'layouts/navbar' %>
        <%= render 'layouts/flash_messages' %>
        <%= yield %>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
        <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    </body>
</html>

app/views/posts/_posts.html.erb
<div id="post">
    <ul class="pt-3 mt-5">
        <% posts.each do |post| %>
            <li class="mr-2 p-2" id="content">
                <div class="d-flex justify-content-sm-between mr-1">
                    <div class="d-flex align-items-center">
                        <% if post.user.image.present? %>
                            <%= image_tag post.user.image.to_s, size: 50, class: 'rounded' %>
                        <% else %>
                            <%= image_tag 'giga_kaeru110-2.png', size: 50, class: 'rounded' %>
                        <% end %>
                        <div class="d-flex" id="post-name">
                            <%= link_to post.user.name, user_path(post.user), class: 'mt-3 text-decoration-none text-dark'%>
                        </div>
                        <div class="mt-2" id="time">
                            <%= post.created_at.to_s(:datetime_jp) %>
                        </div>
                    </div>
                    <% if logged_in? %>
                        <div class="d-flex align-items-center mt-4">
                            <% if current_user == post.user %>
                                <%= link_to post, method: :delete, class: 'pl-1' do %>
                                    <i class="far fa-trash-alt"></i>
                                <% end %>
                            <% end %>
                            <%= render 'favorites/favorite_button', post: post %>
                        </div>
                    <% end %>
                </div>
                <div id="post-content" class="mr-3 ml-4 p-1 pt-5">
                    <p><%= post.content %></p>
                    <p><%= post.two_content %></p>
                    <p><%= post.three_content %></p>
                    <p><%= post.four_content %></p>
                    <p><%= post.five_content %></p>
                </div>
                <div id="post-tag">
                    <%= post.hashtag.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/){|word| link_to word, "/post/tag/#{word.delete("#")}"}.html_safe %>
                </div>
            </li>
        <% end %>
        <div id="post-page">
            <%= paginate posts %>
        </div>
    </ul>
</div>

app/views/posts/index.html.erb
<%= render 'posts/posts', posts: @posts %>

app/views/posts/new.html.erb
<div class="col-sm-6 offset-sm-3">
    <h2 class="text-center border-bottom p-3">投稿</h2>
</div>
<div class="col-sm-6 offset-sm-3 mt-4">
    <%= form_with(model: @post, local:true) do |f| %>
    
        <%= render 'layouts/error_messages', model: f.object %>
        
        <div class="border-bottom p-3">
            <div class="form-group row">
                <%= f.label :content, '五：', class: 'col-sm-1 col-form-label'%>
                <div class="col-sm-11">
                    <%= f.text_field :content, class: 'form-control' %>
                </div>
            </div>
            
            <div class="form-group row">
                <%= f.label :two_content, '七：', class: 'col-sm-1 col-form-label'%>
                <div class="col-sm-11">
                    <%= f.text_field :two_content, class: 'form-control' %>
                </div>
            </div>
            
            <div class="form-group row">
                <%= f.label :three_content, '五：', class: 'col-sm-1 col-form-label'%>
                <div class="col-sm-11">
                    <%= f.text_field :three_content, class: 'form-control' %>
                </div>
            </div>
            
            <div class="form-group row">
                <%= f.label :four_content, '七：', class: 'col-sm-1 col-form-label'%>
                <div class="col-sm-11">
                    <%= f.text_field :four_content, class: 'form-control' %>
                </div>
            </div>
            
            <div class="form-group row">
                <%= f.label :five_content, '七：', class: 'col-sm-1 col-form-label'%>
                <div class="col-sm-11">
                    <%= f.text_field :five_content, class: 'form-control' %>
                </div>
            </div>
            
            <div class="d-flex text-white">
                <%= image_tag 'giga_kaeru110-2.png', size: 50, class: 'd-flex rounded mt-1' %>
                <div class="col-sm-11 ml-4">
                    <div class="balloon4 m-0 mt-1">
                        <p>思いつかなかったら他の人の投稿を見るのもいいかも。。。！！</p>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="border-bottom p-4 mt-2">
            <div class="form-group">
                <%= f.label :hashtag, '#タグ：'%>
                <%= f.text_field :hashtag, class: 'form-control' %>
            </div>
        </div>
        
        <div class="form-group mt-3 text-center">
            <%= button_tag type: 'submit', class: "btn btn-outline-light" do %>
                投稿<i class="far fa-paper-plane ml-2"></i>
            <% end %>
        </div>
    <% end %>
</div>

app/views/posts/tag.html.erb
<%= render 'posts/posts', posts: @post %>

app/views/staticspages/about.html.erb
<h3 class="col-sm-10 offset-sm-1 p-4 text-white" id="about-header">~はじめての詩歌ガイド~</h3>
<div class="col-sm-10 offset-sm-1 mt-4 border-bottom pb-4">
    <div class="p-3 mt-3 border-bottom">
        <h3>1)作品(俳句・川柳・短歌)を作ってみよう</h3>
        <p class="mt-4">
            ・入力フォームの上から３段目までで五、七、五を作り投稿ボタンを押せば俳句（川柳）として投稿できます。
            <br></br>また、追加で七、七を入力すれば短歌として投稿できます。
            <br></br>ちなみに大まかに俳句と川柳の違いは季語が入っているかいないかです（諸説あり）。このサービスにおいては詳しく分類しておりません。
        </p>
        <div id="about-img" class="p-2 ml-2 text-center">
            <img src="https://i.gyazo.com/3747267b5a060e0e2950ac9c81a7e1de.png" alt="Image from Gyazo" width=75%/>
        </div>
    </div>
        
    <div class="p-3 mt-3 border-bottom">
        <h3>2)#タグの作成</h3>
        <p class="mt-4">・投稿に関連のある言葉に「＃」を付けて投稿してみましょう。</p>
        <div id="about-img" class="p-2 ml-2 text-center">
            <img src="https://i.gyazo.com/51afd81ca83685344fd889f77c5371c0.png" alt="Image from Gyazo" width=75%/>
        </div>
    </div>
        
    <div class="p-3 mt-3 border-bottom">
        <h3>3)作品の投稿</h3>
        <p class="mt-4">・作品ができたら投稿ボタンを押して作品を発表してみましょう。</p>
        <div id="about-img" class="p-2 ml-2 text-center">
            <img src="https://i.gyazo.com/f83a1f01beec6a254647aabec947c7ae.png" alt="Image from Gyazo" width=75%/>
        </div>
    </div>
</div>

app/views/users/_form.html.erb
<div class="col-sm-6 offset-sm-3">
    <%= form_with(model: @user, local: true) do |f| %>
        
        <%= render 'layouts/error_messages', model: f.object %>
        
        <div class="border-bottom p-3">
        <div class="form-group">
            <%= f.label :name, '名前：' %>
            <%= f.text_field :name, class: 'form-control'%>
        </div>
        
        <div class="form-group">
            <%= f.label :email, 'メールアドレス：' %>
            <%= f.email_field :email, class: 'form-control'%>
        </div>
        
        <div class="form-group">
            <%= f.label :password, 'パスワード：' %>
            <%= f.password_field :password, class: 'form-control'%>
        </div>
        
        <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード確認：' %>
            <%= f.password_field :password_confirmation, class: 'form-control'%>
        </div>
        
        <div class="form-group">
            <%= f.label :image, 'プロフィール画像：' %>
            <%= f.file_field :image, class: 'form-control-file'%>
        </div>
        
        <div class="form-group">
            <%= f.label :profile, 'プロフィール：' %>
            <%= f.text_area :profile, class: 'form-control'%>
        </div>
        
        </div>
        
        <div class="form-group mt-4 text-center">
            <%= button_tag type: 'submit', class: "btn btn-outline-light" do %>
                登録<i class="far fa-paper-plane ml-2"></i>
            <% end %>
        </div>
    <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/likes.html.erb
<%= render 'posts/posts', posts: @likes %>

app/views/users/new.html.erb
<div class="col-sm-6 offset-sm-3 mt-3 mb-3">
    <h2 class="text-center border-bottom p-3">新規登録</h2>
</div>

<%= render 'form' %>

<div class="col-sm-6 offset-sm-3 mt-3 mb-3">
    <div class="text-center">
        登録済みの方はこちら→<%= link_to 'ログイン', login_path, class: 'btn btn-outline-dark' %>
    </div>
</div>

app/views/users/show.html.erb
<div class="col-sm-10 offset-sm-1">
    <div class="media d-flex align-items-center border-bottom p-4">
        <div class="pl-2" id="show-image">
            <% if @user.image.present? %>
                <%= image_tag @user.image.to_s, size: 150, class: 'rounded-circle' %>
            <% else %>
                <%= image_tag 'giga_kaeru110-2.png', size: 150, class: 'rounded' %>
            <% end %>
        </div>
        <div class="media-body p-4">
            <h4 class="border-bottom"><%= @user.name %></h4>
            <p class="border-bottom pb-4">
                <% if @user.profile.present? %>
                    <%= @user.profile %>
                <% else %>
                    <%= 'よろしくお願いします！'%>
                <% end %>
            </p>
            <% if current_user == @user %>
                <%= link_to edit_user_url, class: 'btn btn-outline-light' do %>
                    編集<i class="fas fa-pen ml-2"></i>
                <% end %>
            <% end %>
        </div>
    </div>
    <ul class="mt-4 pr-4 pl-4">
        <%= paginate @post %>
        <% @post.each do |post| %>
            <li class="mt-2 border-bottom">
                <div class="row p-2">
                    <div class="offset-sm-2 col-sm-10">
                        <div class="d-flex align-items-center mb-2">
                            <%= post.created_at.to_s(:datetime_jp) %>
                            <% if current_user == post.user %>
                                <%= link_to post, method: :delete, class: 'btn-sm' do %>
                                    <i class="far fa-trash-alt"></i>
                                <% end %>
                            <% end %>
                            <div class="pt-1">
                                <%= render 'favorites/favorite_button', post: post %>
                            </div>
                        </div>
                        <h4>
                            <%= post.content %>
                            <%= post.two_content %>
                            <%= post.three_content %>
                            <%= post.four_content %>
                            <%= post.five_content %>
                        </h4>
                    </div>
                </div>
            </li>
        <% end %>
        <%= paginate @post %>
    </ul>
</div>